name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Swift Packages Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('FoodTaskerMobile.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

      - name: Clear Cache
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Run Tests (No Cache)
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle exec fastlane unit_test

      - name: Run Tests (Cache)
        if: steps.cache.outputs.cache-hit == 'true'
        run: bundle exec fastlane unit_test --skip_package_dependencies_resolution true
